### ISSUE TITLE
avoid warnings when implementing Angular callbacks

### ISSUE THREAD

**Issue by ursmeili** [IPWright83/eslint-plugin-async-protect#14]
When your library is used on an Angular project, we get lots of warnings when implementing Angular callbacks such as "ngOnInit". Obviously I can't change the method's name.
![grafik](https://user-images.githubusercontent.com/23562434/162742950-c0e0b322-0ef1-4e7b-8e66-dca2501f0479.png)

Is there any solution for this, apart from cluttering our code base with `// eslint-disable-next-line async-protect/async-suffix` comments?

**Comment by IPWright83** [comment]
@ursmeili I haven't used Angular (honestly I didn't expect this library to be used in a TypeScript project either). Are these names pretty consistent? I wonder if adding a set of  excluded function names would work for this rule?

**Comment by ursmeili** [comment]
Hi Ian,
There are a bunch of interfaces an Angular developer usually implements.
That means if we could include all the function names mentioned in
https://angular.io/guide/lifecycle-hooks#lifecycle-event-sequence in an
exclude list we would solve the problem.
Regards,
Urs

**Comment by IPWright83** [comment]
I'd need to work out how to pass additional config, but I feel like if there was a config setting `angular: true` then it'd be quite easy to exclude by adding an additional check around https://github.com/IPWright83/eslint-plugin-async-protect/blob/master/src/async-await.js#L64 and https://github.com/IPWright83/eslint-plugin-async-protect/blob/master/src/async-suffix.js#L39 to basically exclude checking if the name is contained within that list.

I don't actually use the library myself at the moment, I'll try and see if I can find some time, but I'd welcome a PR if you're comfortable suggesting a change yourself?
